# Generated by Django 3.1.3 on 2021-01-14 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="You musn't use symbols", max_length=300, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(max_length=2000)),
                ('meta_desc', models.TextField(max_length=1000)),
                ('meta_keywords', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_topic', models.CharField(help_text="You musn't use symbols", max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(max_length=2000)),
                ('meta_desc', models.TextField(max_length=1000)),
                ('meta_keywords', models.CharField(max_length=1000)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rep.topic')),
            ],
            options={
                'ordering': ('-topic',),
            },
        ),
    ]
