# Generated by Django 3.1.3 on 2021-01-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rep', '0003_auto_20210114_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='meta_keywords',
            field=models.CharField(max_length=1000),
        ),
    ]
